<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <IsPackable>false</IsPackable>
    <Copyright>Copyright (c) 2021 Einar Saukas; Copyright (c) 2026 Robbert van Dalen</Copyright>
  </PropertyGroup>
</Project>
