<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dnt4</AssemblyName>
    <PackageId>Nt4.Decompressor.Tool</PackageId>
    <RootNamespace>Nt4.CommandLine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Nt4/Nt4.csproj" />
  </ItemGroup>
</Project>
